name: wrestling_scoreboard_server
description: Server for a wrestling scoreboard.
version: 0.3.9
homepage: https://server.wrestling-scoreboard.oberhauser.dev
resolution: workspace
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  dotenv: ^4.1.0
  shelf: ^1.0.0
  shelf_router: ^1.1.2
  shelf_static: ^1.0.0
  wrestling_scoreboard_common:
    path: ../wrestling_scoreboard_common
  postgres: ^3.0.6
  web_socket_channel: ^3.0.2
  shelf_web_socket: ^3.0.0
  pubspec_parse: ^1.2.3
  collection: ^1.19.0
  logging: ^1.2.0
  dart_jsonwebtoken: ^3.1.1
  pub_semver: ^2.1.4
  stack_trace: ^1.12.1
  country: ^6.0.2
  http: ^1.5.0
  timezone: ^0.10.1
  mailer: ^6.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0
